#!/bin/bash

"""
cat /etc/nginx/sites-available/darin

server {
        listen 80;
        listen [::]:80;
        root /var/www/html/darin;
        index index.html index.htm index.nginx-debian.html;
        server_name darin.htp-ipv6.tech;
        location / {
                try_files $uri $uri/ =404;
        }
}
"""

"""
cat /var/lib/bind/htp-ipv6.tech
$ttl 3600
htp-ipv6.tech.  IN      SOA     a.htp-ipv6.tech. admin.quel.tech. (
                        0204061219
                        3600
                        3600
                        3600
                        3600 )

htp-ipv6.tech.          IN      NS      a.htp-ipv6.tech.
htp-ipv6.tech.          IN      NS      b.htp-ipv6.tech.
a.htp-ipv6.tech.        IN      AAAA    2400:6180:0:d0::f8:d001
b.htp-ipv6.tech.        IN      AAAA    2400:6180:0:d0::f8:d001
a.htp-ipv6.tech.        IN      A       128.199.252.56
b.htp-ipv6.tech.        IN      A       128.199.252.56
htp-ipv6.tech.          IN      AAAA    2400:6180:0:d0::f8:d001
htp-ipv6.tech.          IN      A       128.199.252.56
htp-ipv6.tech.          IN      MX      10 mail.htp-ipv6.tech.
mail.htp-ipv6.tech.     IN      AAAA    2400:6180:0:d0::f8:d001
mail.htp-ipv6.tech.     IN      A       128.199.252.56
"""

#file that is modified :
#/etc/nginx/sites-available/username
#/etc/nginx/sites-enabled/username
#/var/www/html/username
#/var/lib/bind/username
#/var/lib/bind/htp-ipv6.tech
#/etc/bind/named.conf.local
#/home/username
#userdel 

LISTUSER=$(awk -F':' '{ print $1}' /etc/passwd | sed 1,31d | tr '\n' ' ,')

echo -e "\n"
echo -e "==================================================\n"
echo -e "User already registered is : \n"
echo -e "${LISTUSER} \n"
sleep 2
echo -e "==================================================\n"
echo -e "Step 1. Adding User. Make sure user is not exist \n"
echo -e "==================================================\n"
read -p "Please enter username : " USERNAME
echo -e "PasswordSementara123\nPasswordSementara123" | adduser --gecos "" ${USERNAME}
sleep 3

echo -e "==================================================\n"
echo -e "Step 2. Restart Postfix \n"
systemctl restart postfix 
sleep 3

echo -e "==================================================\n"
echo -e "Step 3. Adding Nginx Config \n"
cp /etc/nginx/sites-available/darin /etc/nginx/sites-available/${USERNAME}
sed -i "s/darin/${USERNAME}/g" /etc/nginx/sites-available/${USERNAME}
ln -s /etc/nginx/sites-available/${USERNAME} /etc/nginx/sites-enabled/
sleep 3

echo -e "==================================================\n"
echo -e "Step 4. Adding Subdomain Document Root\n"
mkdir /var/www/html/${USERNAME}
cp /var/www/html/darin/index.nginx-debian.html /var/www/html/${USERNAME}/
chmod -R 777 /var/www/html/${USERNAME}
sleep 3

echo -e "==================================================\n"
echo -e "Step 5. Restart Nginx \n"
systemctl restart nginx
sleep 3

echo -e "==================================================\n"
echo -e "Step 6. Adding Zone for DNS Server \n"
cp /var/lib/bind/darin.htp-ipv6.tech.hosts /var/lib/bind/${USERNAME}.htp-ipv6.tech.hosts
sed -i "s/darin/${USERNAME}/g" /var/lib/bind/${USERNAME}.htp-ipv6.tech.hosts
sleep 3

echo -e "\n\n"
echo "zone "\""${USERNAME}.htp-ipv6.tech"\"" {" >> /etc/bind/named.conf.local
echo '        type master;' >> /etc/bind/named.conf.local
echo "        file "\""/var/lib/bind/${USERNAME}.htp-ipv6.tech.hosts"\"";" >> /etc/bind/named.conf.local
echo '        };' >> /etc/bind/named.conf.local

echo -e "\n\n"
echo "${USERNAME}.htp-ipv6.tech.      IN      AAAA    2400:6180:0:d0::f8:d001" >> /var/lib/bind/htp-ipv6.tech.hosts
echo "a.${USERNAME}.htp-ipv6.tech.      IN      AAAA    2400:6180:0:d0::f8:d001" >> /var/lib/bind/htp-ipv6.tech.hosts
echo "b.${USERNAME}.htp-ipv6.tech.      IN      AAAA    2400:6180:0:d0::f8:d001" >> /var/lib/bind/htp-ipv6.tech.hosts
echo "${USERNAME}.htp-ipv6.tech.  IN      NS      a.${USERNAME}.htp-ipv6.tech." >> /var/lib/bind/htp-ipv6.tech.hosts
echo "${USERNAME}.htp-ipv6.tech.  IN      NS      b.${USERNAME}.htp-ipv6.tech." >> /var/lib/bind/htp-ipv6.tech.hosts
sleep 3

systemctl restart bind9
sleep 3

echo -e "==================================================\n"
echo -e "Step 7. Finish, please verify\n"
echo -e "==================================================\n"
echo -e "Execute this command "
echo -e "- systemctl restart bind9"
echo -e "- named-checkzone htp-ipv6.tech /var/lib/bind/htp-ipv6.tech.hosts"
echo -e "- systemctl status bind9"
echo -e "- dig @localhost ${USERNAME}.htp-ipv6.tech AAAA +short"
echo -e "- dig @localhost ${USERNAME}.htp-ipv6.tech NS +short"
echo -e "\n"
